### ISSUE TITLE
Not getting data or How to refere data from json_table

### ISSUE THREAD

**Issue by daxlai** [ainielse/get_ig_data#1]
I developed one sample application using this plugin and try to access data from json_table but unable to get it. I use standard dept table from sample emp dataset. My actions are recorded and access using following link. even I share my application only two object is to create in schema.
[action:](https://drive.google.com/file/d/1Hxvg_lWqWVpIpmoTjc2O_09NgC85XBtw/view?usp=sharing)

[application](https://drive.google.com/file/d/1dn7IHIp6PxQyUGb4mWJFKevwLcVpytc7/view?usp=sharing)

https://drive.google.com/file/d/1dn7IHIp6PxQyUGb4mWJFKevwLcVpytc7/view?usp=sharing

table
CREATE TABLE LOCATE_ERR
(
  STR  VARCHAR2(2000 BYTE)
);
CREATE OR REPLACE procedure 
err_fnct(ERRstr in varchar2)  IS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
   INSERT INTO locate_err VALUES (ERRstr);
   commit;
END;

**Comment by daxlai** [comment]
actually my mistake i got my problem

**Comment by daxlai** [comment]
actully my problem writing wrong name of field.

**Comment by ainielse** [comment]
Hi daxlai,

Glad you solved it. Just a tip...If you view the browser console log it will give you the select statement to use in your dynamic action. Hope that helps.

Best,

Anton
